ekyna_order_order_admin_home:
    path: /
    defaults: { _controller: "ekyna_order.order.controller:homeAction" }
    requirements:
        _method: GET

ekyna_order_order_admin_list:
    path: /list
    defaults: { _controller: "ekyna_order.order.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_order_order_admin_new:
    path: /new
    defaults: { _controller: "ekyna_order.order.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_order_order_admin_show:
    path: /{orderId}/show
    defaults: { _controller: "ekyna_order.order.controller:showAction" }
    requirements:
        _method: GET
        orderId:  \d+

ekyna_order_order_admin_edit:
    path: /{orderId}/edit
    defaults: { _controller: "ekyna_order.order.controller:editAction" }
    requirements:
        _method: GET|POST
        orderId:  \d+

ekyna_order_order_admin_remove:
    path: /{orderId}/remove
    defaults: { _controller: "ekyna_order.order.controller:removeAction" }
    requirements:
        _method: GET|POST
        orderId:  \d+

ekyna_order_order_admin_add_item:
    path: /{orderId}/add-item
    defaults: { _controller: "ekyna_order.order.controller:addItemAction" }
    requirements:
        _method: GET|POST
        orderId:  \d+
