ekyna_order_tax_admin_home:
    path: ""
    defaults: { _controller: "ekyna_order.tax.controller:homeAction" }
    methods: [GET]

ekyna_order_tax_admin_list:
    path: /list
    defaults: { _controller: "ekyna_order.tax.controller:listAction" }
    methods: [GET|POST]

ekyna_order_tax_admin_new:
    path: /new
    defaults: { _controller: "ekyna_order.tax.controller:newAction" }
    methods: [GET|POST]

ekyna_order_tax_admin_show:
    path: /{taxId}/show
    defaults: { _controller: "ekyna_order.tax.controller:showAction" }
    methods: [GET]
    requirements:
        taxId: \d+

ekyna_order_tax_admin_edit:
    path: /{taxId}/edit
    defaults: { _controller: "ekyna_order.tax.controller:editAction" }
    methods: [GET|POST]
    requirements:
        taxId: \d+

ekyna_order_tax_admin_remove:
    path: /{taxId}/remove
    defaults: { _controller: "ekyna_order.tax.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        taxId: \d+
